### ISSUE TITLE
Error: Unsupported OS Alpine Linux

### ISSUE THREAD

**Issue by xsteadfastx** [orf/gping#140]
I try to get a alpine linux package for this wonderful tool i'am daily depend on :)

its compiling just fine but when i try to run it i get a blank screen and after doing a CTRL+c i get the error message: `Error: Unsupported OS Alpine Linux`. any ideas to bring this to alpine linux?

here is my APKBUILD file with the build commands i used:

```
# Contributor: Marvin Preuss <marvin@xsteadfastx.org>
# Maintainer: Marvin Preuss <marvin@xsteadfastx.org>
pkgname=gping
pkgver=1.2.1
pkgrel=0
pkgdesc="Ping, but with a graph"
url="https://github.com/orf/gping"
arch="x86_64 x86 armhf armv7 aarch64 ppc64le" # limited by rust/cargo
license="MIT"
depends=""
makedepends="cargo"
options="net"
checkdepends=""
install=""
source="$pkgname-$pkgver.tar.gz::https://github.com/orf/gping/archive/refs/tags/v$pkgver.tar.gz"

export CARGO_HOME="$srcdir"/cargo

build() {
	cargo build --release --locked
}

check() {
	cargo test --release --locked
}

package() {
	install -Dm755 target/release/"$pkgname" "$pkgdir"/usr/bin/"$pkgname"
}
sha512sums="
e74b1f2aa6e51dd0089b020af28c3928c43e0c0ec1a0b32c421277dc536f0ac6c1819e38cb65ec5b458ddd3eea883cd3bcced39f5ed799900bf423e22eb3ecc2  gping-1.2.1.tar.gz
"
```

**Comment by orf** [comment]
Hey! I'm attempting to add support for Alpine now. Unfortunately the `ping` that ships with it by default doesn't support receiving timeout notifications (i.e if there's a timeout there just isn't any output message), which is really sucky.

Otherwise it looks pretty simple. I'm not familiar with Alpine (or MUSL in general), but attempting to run `cargo build` on the project in an Alpine container results in a failure to build a dependency (see https://github.com/rust-lang/rust/issues/40174). Did you do any other magic to get this to compile? According to the above you're also just running `cargo build` which confuses me.

**Comment by orf** [comment]
Ahh, silly me. I needed to run `apk add musl-dev`. I should have Alpine support released soon 👍

**Comment by xsteadfastx** [comment]
On Mo, 19. Jul 14:48, Tom Forbes wrote:
> Hey! I'm attempting to add support for Alpine now. Unfortunately the `ping` that ships with it by default doesn't support receiving timeout notifications (i.e if there's a timeout there just isn't any output message), which is really sucky.
> 
> Otherwise it looks pretty simple. I'm not familiar with Alpine (or MUSL in general), but attempting to run `cargo build` on the project in an Alpine container results in a failure to build a dependency (see https://github.com/rust-lang/rust/issues/40174). Did you do any other magic to get this to compile? According to the above you're also just running `cargo build` which confuses me.

the `ping` that comes with alpine is that that ships with busybox. i
could easily depend gping in alpine for the ping that ships with
`iputils` (https://github.com/iputils/iputils/). maybe that helps!

**Comment by orf** [comment]
Should be fixed in the latest release! I now fall back to detecting the ping version rather than the OS
