### ISSUE TITLE
[Feature request] Add a manpage

### ISSUE THREAD

**Issue by werdahias** [orf/gping#252]
Hi,
I'm just waiting for the clapv4 migration to finalize the gping debian package. Since it is a cli program a manpage would make sense. It could life at the root of the project (and installed from there during the build of the package). I can have a stab at it; it would be nice to have one for gping.

**Comment by orf** [comment]
Hey! I'm ok with adding a manpage, but I personally don't use them and wouldn't know where to start when adding one.

I'm more than happy to  accept even a half-baked manpage from you, to get us started?

**Comment by werdahias** [comment]
I'll work on it tomorrow

**Comment by werdahias** [comment]
This is my draft: [manpage.md](https://github.com/orf/gping/files/10394561/manpage.md)
I'm not sure what values` --interface` takes.  Also please think about generating it with clap-mangen (or similar crates) in case the options/syntax/whatever changes.

**Comment by werdahias** [comment]
see #253

**Comment by ChrissoChrisso** [comment]
I checked the draft and have an enhancement request for it.  Can definitions for the abbreviations in gping's output be added to the manpage?

Asking because it would clear up any uncertainties or misunderstandings about what each field in indicating.

(Initially I was unsure about what the p95 and t/o fields are indicating, but now after googling I assume p95 to mean 95% of ping times have lower latency than the reported p95 time, and that t/o is the number of pings that have timed out since the graph started.)
By the way this is a awesome app!!  Thank you.

**Comment by orf** [comment]
I tried to add clap-mangen in #257, but I'm not really happy with it. I'll try and revisit it.

With regards to adding `t/o` and `p95` to the manpage, sure, but I'm not really sure how 😅. I'll take a look when I have time next week.

I'm going to close this for now as #253 is merged. thanks for the help @werdahias <3

**Comment by orf** [comment]
@werdahias is there any movement on the gping Debian package? Anything I can help with?
