### ISSUE TITLE
Lost packets are not displayed

### ISSUE THREAD

**Issue by matthijskooijman** [orf/gping#57]
I was hoping to use gping to debug intermittent connectivity issues, by running it on multiple hosts with multiple targets to figure out what part of my network occasionally breaks. However, it seems that if ping packets get lost, the display just stops, rather than showing the lost packets. This effectively means that gping is not usable for the case I had in mind. Would it make sense to explicitly show lost packets (this might need to have a timeout, to consider a packet lost after some time, or after the next reply is received, but probably also needs retroactively updating a packet later when it is received after all.

**Comment by vernhart** [comment]
I was able to work around this deficiency by modifying linux_pinger in pinger.py to add:

```
    else:
        return -1
```

And then, I added option `-O` (capitol o) to the gping command, which gets passed to ping and displays some text if a packet hasn't come back when sending out a new packet.
Now, when a packet is missed, it prints a ? instead of a graph line.

**Comment by tylla** [comment]
@vernhart You should make a pull-request...

**Comment by llamafilm** [comment]
How about turning the vertical bar red when the packet is lost?
