### ISSUE TITLE
Use drawille for much improved rendering

### ISSUE THREAD

**Issue by severin-lemaignan** [orf/gping#6]
https://github.com/asciimoo/drawille

**Comment by orf** [comment]
Drawile looks really nice, but at the moment it doesn't support Windows. It doesn't look like that's on the roadmap either, so unfortunately no can do.

**Comment by severin-lemaignan** [comment]
Does not support Windows? what do you mean? As far as I know, Drawille does support Windows... the only prerequisite is that your terminal need to use a rendering font that has the Braille glyphs. But this is unrelated to the operating system. Or am I missing something?

**Comment by orf** [comment]
Unfortunately it imports the `curses` module (https://github.com/asciimoo/drawille/blob/master/drawille.py#L23) which isn't available on Windows. It's only used in one place though, so that could be dealt with, but an implementation to get the terminal size would also need to be added.

AFAICT Windows also doesn't support the braille glyphs/.Also under the hood Drawile seems to be just an implementation of a canvas, so I can't see an immediate benefit and gave up.

**Comment by tylla** [comment]
Maybe this module [windows-curses](https://pypi.org/project/windows-curses/) could be used for curses support.
